/* © 2023 Peter Rodrick <pete@lftlc.xyz> */

const medicalChiefComplaints = [
  {
    complaint: "Chest pain",
    nature: "Cardiac",
    responsiveness: "Responsive: Alert",
    airway: "Clear",
    breathing: "Normal",
    circulation: "Pulse present",
  },
  {
    complaint: "Shortness of breath",
    nature: "Respiratory",
    responsiveness: "Responsive: to Verbal",
    airway: "May be compromised",
    breathing: "Labored",
    circulation: "Pulse present",
  },
  {
    complaint: "Abdominal pain",
    nature: "Gastrointestinal",
    responsiveness: "Responsive: to Pain",
    airway: "Clear",
    breathing: "Normal",
    circulation: "Pulse present",
  },
  {
    complaint: "Headache",
    nature: "Neurological",
    responsiveness: "Responsive: Alert",
    airway: "Clear",
    breathing: "Normal",
    circulation: "Pulse present",
  },
  {
    complaint: "Dizziness",
    nature: "Neurological",
    responsiveness: "Responsive: Alert",
    airway: "Clear",
    breathing: "Normal",
    circulation: "Pulse present",
  },
  {
    complaint: "Nausea",
    nature: "Gastrointestinal",
    responsiveness: "Responsive: to Verbal",
    airway: "Clear",
    breathing: "Normal",
    circulation: "Pulse present",
  },
  {
    complaint: "Vomiting",
    nature: "Gastrointestinal",
    responsiveness: "Responsive: to Pain",
    airway: "May be compromised",
    breathing: "Normal",
    circulation: "Pulse present",
  },
  {
    complaint: "Allergic reaction",
    nature: "Allergic/Immunologic",
    responsiveness: "Responsive: Alert",
    airway: "May be compromised",
    breathing: "Normal",
    circulation: "Pulse present",
  },
  {
    complaint: "Seizure",
    nature: "Neurological",
    responsiveness: "Responsive: to Pain",
    airway: "May be compromised",
    breathing: "Labored",
    circulation: "Pulse present",
  },
  {
    complaint: "Fever",
    nature: "Infectious",
    responsiveness: "Responsive: Alert",
    airway: "Clear",
    breathing: "Normal",
    circulation: "Pulse present",
  },
  {
    complaint: "Cardiac arrest",
    nature: "Cardiac",
    responsiveness: "Unresponsive",
    airway: "May be compromised",
    breathing: "Absent",
    circulation: "Pulse absent",
  },
];

const traumaChiefComplaints = [
  {
    complaint: "Motor vehicle accident",
    mechanism: "Blunt trauma",
    responsiveness: "Responsive: Alert",
    airway: "May be compromised",
    breathing: "Labored",
    circulation: "Pulse present",
  },
  {
    complaint: "Fall from height",
    mechanism: "Fall",
    responsiveness: "Responsive: to Pain",
    airway: "May be compromised",
    breathing: "Labored",
    circulation: "Pulse present",
  },
  {
    complaint: "Bicycle accident",
    mechanism: "Blunt trauma",
    responsiveness: "Responsive: to Pain",
    airway: "May be compromised",
    breathing: "Labored",
    circulation: "Pulse present",
  },
  {
    complaint: "Assault",
    mechanism: "Blunt or penetrating trauma",
    responsiveness: "Responsive: to Pain",
    airway: "May be compromised",
    breathing: "Labored",
    circulation: "Pulse present",
  },
  {
    complaint: "Sports injury",
    mechanism: "Blunt trauma",
    responsiveness: "Responsive: Alert",
    airway: "Clear",
    breathing: "Normal",
    circulation: "Pulse present",
  },
  {
    complaint: "Burn",
    mechanism: "Burn",
    responsiveness: "Responsive: Alert",
    airway: "May be compromised",
    breathing: "Labored",
    circulation: "Pulse present",
  },
  {
    complaint: "Penetrating trauma",
    mechanism: "Penetrating trauma",
    responsiveness: "Responsive: to Pain",
    airway: "May be compromised",
    breathing: "Labored",
    circulation: "Pulse present",
  },
  {
    complaint: "Animal bite",
    mechanism: "Bite",
    responsiveness: "Responsive: to Pain",
    airway: "May be compromised",
    breathing: "Labored",
    circulation: "Pulse present",
  },
  {
    complaint: "Electrical injury",
    mechanism: "Electrical injury",
    responsiveness: "Responsive: to Pain",
    airway: "May be compromised",
    breathing: "Labored",
    circulation: "Pulse present",
  },
  {
    complaint: "Crush injury",
    mechanism: "Crush injury",
    responsiveness: "Responsive: to Pain",
    airway: "May be compromised",
    breathing: "Labored",
    circulation: "Pulse present",
  },
];

const getRandomChiefComplaint = (chiefComplaints) => {
  const randomIndex = Math.floor(Math.random() * chiefComplaints.length);
  return chiefComplaints[randomIndex];
};

/*
const safety = ["yes", "no"];

const hazard = ["none", "yes-combative", "yes-fire"];

const mechanism = {
  beach,
};

const buildTraumaAssessment = (location, patients, age, sex) => {};

const trauma = {
  single: {
    observed: {
      beach: [
        {
          id: 1,
          safe: "Yes",
          hazard: "None",
          treatmentConsent: "Verbal",
          mechanism: "Running",
          additionalEMS: "Yes",
          cSpine: "No",
          generalImpression: "Seated, holding leg, wincing",
          avpu: "Alert",
          loc: "4",
          alteredMentalStatus: "No",
          chiefComplaint: "Ankle pain",
          airway: "Open",
          airwayCompromise: "None",
          ventilationRate: "Normal",
          ventilationQuality: "Normal",
          supplementalOxygen: "No",
          supplementalOxygenRoute: "N/A",
          supplementalOxygenRate: "N/A",
          pulse: "Yes",
          skinColor: "Pink",
          skinTemperature: "Warm",
          skinCondition: "Moist",
          majorBleed: "None",
          majorBleedLocation: "None",
          shock: "No",
          gcs: "14",
          treatTransport: "Transport",
          vitalPulse: "96",
          vitalRespiration: "18",
          vitalBP: "130/P",
          painOnset: "Sudden",
          painBetter: "Nothing",
          painWorse: "Movement",
          painQuality: "Sharp",
          painRadiation: "Localized",
          painSeverity: "10",
          painTime: "10 minutes",
          historyObtainable: "Yes",
          historySigns: "Ankle deformity",
          historySymptoms: "Light-headedness",
          historyAllergies: "None",
          historyMedications: "None",
          historyPertinent: "None",
          historyLastIntake: "Water, Bagel",
          historyEvents: "Tripped while running",
          secondaryObtainable: "Yes",
          secondaryHeadScalpEars: "Normal",
          secondaryHeadEyes: "PERL @ 4mm",
          secondaryHeadMouthNoseFace: "Normal",
          secondaryNeckTrachea: "Normal",
          secondaryNeckJugularVeins: "Normal",
          secondaryNeckCSpine: "Normal",
          secondaryChestInspect: "Normal",
          secondaryChestAusculate: "Normal bilateral",
          secondaryAbdomenPalpate: "Normal",
          secondaryPelvis: "Normal",
          secondaryGenitaliaNeeded: "No",
          secondaryGenitalia: "Unknown",
          secondaryLowerExtremityLeft: "Ankle deformity",
          secondaryLowerExtremityLeftPMS: "Normal",
          secondaryLowerExtremityRight: "Normal",
          secondaryLowerExtremityRightPMS: "Normal",
          secondaryUpperExtremityLeft: "Elbow scrape",
          secondaryUpperExtremityLeftPMS: "Normal",
          secondaryUpperExtremityRight: "Normal",
          secondaryUpperExtremityRightPMS: "Normal",
          secondaryPosteriorThorax: "Normal",
          secondaryPosteriorLumbar: "Normal",
          secondaryPosteriorButtocks: "Normal",
          relatedProtocolName: "Trauma-Extremity",
          relatedProtocolID: "S-139",
          relatedProtocolBLSInterventions:
            "Splint neurologically stable fractures in position as presented. Traction splint PRN. Reduce grossly angulated long bone fractures with no pulse or sensation PRN BHO. Direct pressure to control external hemorrhage. Apply gauze or hemostatic dressing PRN. Tourniquet PRN. In MCI, direct pressure not required prior to tourniquet application.",
          secondaryRelatedProtocolName: "Pain Management",
          secondaryRelatedProtocolID: "S-141",
          secondaryRelatedProtocolBLSInterventions:
            "Assess level of pain. Ice, immobilize, and splint PRN. Elevation of extremity PRN.",
          reassessmentTime: "15 minutes",
          reassessmentObtainable: "No",
        },
      ],
      water: [{ name: "Random", id: 1 }],
      jetty: [{ name: "Random", id: 1 }],
      boardwalk: [{ name: "Random", id: 1 }],
    },
    repCall: {
      beach: [{ name: "Random", id: 1 }],
      water: [{ name: "Random", id: 1 }],
      jetty: [{ name: "Random", id: 1 }],
      boardwalk: [{ name: "Random", id: 1 }],
    },
  },
  multi: {
    observed: {
      beach: [{ name: "Random", id: 1 }],
      water: [{ name: "Random", id: 1 }],
      jetty: [{ name: "Random", id: 1 }],
      boardwalk: [{ name: "Random", id: 1 }],
    },
    repCall: {
      beach: [{ name: "Random", id: 1 }],
      water: [{ name: "Random", id: 1 }],
      jetty: [{ name: "Random", id: 1 }],
      boardwalk: [{ name: "Random", id: 1 }],
    },
  },
};
*/
