/* © 2023 Peter Rodrick <pete@lftlc.xyz> */

const trauma = {
  single: {
    observed: {
      beach: [
        {
          id: 1,
          safe: "Yes",
          hazard: "None",
          mechanism: "Running",
          additionalEMS: "Yes",
          cSpine: "No",
          generalImpression: "Seated, holding leg, wincing",
          loc: "4",
          chiefComplaint: "Ankle pain",
          airway: "Open",
          airwayCompromise: "None",
          ventilationRate: "Normal",
          ventilationQuality: "Normal",
          oxygen: "No",
          pulse: "Yes",
          skinColor: "Pink",
          skinTemperature: "Warm",
          skinCondition: "Moist",
          majorBleed: "None",
          majorBleedLocation: "None",
          shock: "No",
          gcs: "14",
          treatTransport: "Transport",
          vitalPulse: "96",
          vitalRespiration: "16",
          vitalBP: "130/P",
          painOnset: "Sudden",
          painBetter: "Nothing",
          painWorse: "Movement",
          painQuality: "Sharp",
          painRadiation: "Localized",
          painSeverity: "10",
          painTime: "10 minutes",
          historyObtainable: "Yes",
          historySigns: "Ankle deformity",
          historySymptoms: "Light-headedness",
          historyAllergies: "None",
          historyMedications: "None",
          historyPertinent: "None",
          historyLastIntake: "Water, Bagel",
          historyEvents: "Tripped while running",
          secondaryObtainable: "Yes",
          secondaryHeadScalpEars: "Normal",
          secondaryHeadEyes: "PERL @ 4mm",
          secondaryHeadMouthNoseFace: "Normal",
          secondaryNeckTrachea: "Normal",
          secondaryNeckJugularVeins: "Normal",
          secondaryNeckCSpine: "Normal",
          secondaryChestInspect: "Normal",
          secondaryChestAusculate: "Normal bilateral",
          secondaryAbdomenPalpate: "Normal",
          secondaryPelvis: "Normal",
          secondaryGenitaliaNeeded: "No",
          secondaryGenitalia: "Unknown",
          secondaryLowerExtremityLeft: "Ankle deformity",
          secondaryLowerExtremityLeftPMS: "Normal",
          secondaryLowerExtremityRight: "Normal",
          secondaryLowerExtremityRightPMS: "Normal",
          secondaryUpperExtremityLeft: "Elbow scrape",
          secondaryUpperExtremityLeftPMS: "Normal",
          secondaryUpperExtremityRight: "Normal",
          secondaryUpperExtremityRightPMS: "Normal",
          secondaryPosteriorThorax: "Normal",
          secondaryPosteriorLumbar: "Normal",
          secondaryPosteriorButtocks: "Normal",
          reassessmentTime: "15 minutes",
          reassessmentObtainable: "No",
        },
      ],
      water: [{ name: "Random", id: 1 }],
      jetty: [{ name: "Random", id: 1 }],
      boardwalk: [{ name: "Random", id: 1 }],
    },
    repCall: {
      beach: [{ name: "Random", id: 1 }],
      water: [{ name: "Random", id: 1 }],
      jetty: [{ name: "Random", id: 1 }],
      boardwalk: [{ name: "Random", id: 1 }],
    },
  },
  multi: {
    observed: {
      beach: [{ name: "Random", id: 1 }],
      water: [{ name: "Random", id: 1 }],
      jetty: [{ name: "Random", id: 1 }],
      boardwalk: [{ name: "Random", id: 1 }],
    },
    repCall: {
      beach: [{ name: "Random", id: 1 }],
      water: [{ name: "Random", id: 1 }],
      jetty: [{ name: "Random", id: 1 }],
      boardwalk: [{ name: "Random", id: 1 }],
    },
  },
};
